---
platform: linux

image_resource:
  type: docker-image
  source: {repository: cloudfoundry/cflinuxfs2}
  
inputs:
  - name: cookbook-template-repo
  - name: hugo
  - name: password-site

outputs:
  - name: compiled-site

run:
  path: cookbook-template-repo/ci/tasks/hugo.sh
