---
platform: linux

image_resource:
  type: docker-image
  source: {repository: node}

inputs:
  - name: documentation-repo
  - name: compiled-site

outputs:
  - name: indexed-site

run:
  path: documentation-repo/ci/tasks/index.sh
