resources:

- name: hugo
  type: github-release
  source:
    user: gohugoio
    repository: hugo
    access_token: {{github_token}}
- name: documentation-repo
  type: git
  source:
    uri: {{git_repo_uri}}
    branch: {{git_branch}}
    private_key: {{github_token}}
- name: pws
  type: cf
  source:
      api: {{cf_api}}
      organization: {{cf_org}}
      space: {{cf_space}}
      username: {{cf-username}}
      password: {{cf-password}}
      skip_cert_check: true

jobs:
- name: compile-site
  plan:
  - get: documentation-repo
    params:
      submodules: all
    trigger: true

  - get: hugo
    params:
      globs:
      - '*Linux-64bit.tar.gz'
  
  - task: compile-site
    file: documentation-repo/ci/tasks/hugo.yml
  
  - task: index-site
    file: documentation-repo/ci/tasks/index.yml

  - put: pws
    params:
       manifest: indexed-site/manifest.yml
       path: indexed-site
