resources:

- name: hugo
  type: github-release
  source:
    user: gohugoio
    repository: hugo
    access_token: {{github_api_token}}
- name: documentation-repo
  type: git
  source:
    uri: {{git_repo_uri}}
    branch: {{git_branch}}
    private_key: {{github_token}}
- name: pws
  type: cf
  source:
      api: {{cf_api}}
      organization: {{cf_org}}
      space: {{cf_space}}
      username: {{cf-username}}
      password: {{cf-password}}
      skip_cert_check: true

jobs:
- name: compile-site
  plan:
  - get: documentation-repo
    params:
      submodules: all
    trigger: true

  - get: hugo
    params:
      globs:
      - '*Linux-64bit.tar.gz'

  - task: generate-auth
    file: documentation-repo/ci/tasks/htpasswd.yml
    params:
      SITE_USER: {{site_user}}
      SITE_PASSWORD: {{site_password}}
  
  - task: compile-site
    file: documentation-repo/ci/tasks/hugo.yml

  - put: pws
    params:
       manifest: compiled-site/manifest.yml
       path: compiled-site
