resources:

- name: hugo
  type: github-release
  source:
    user: spf13
    repository: hugo
    access_token: {{github_token}}
- name: documentation-repo
  type: git
  source:
    uri: {{git_repo_uri}}
    branch: master
    private_key: {{git_private_key}}
- name: prod
  type: cf
  source:
      api: {{api}}
      organization: {{org}}
      space: {{space}}
      username: {{cf-username}}
      password: {{cf-password}}
      skip_cert_check: true

jobs:
- name: compile-site
  plan:
  - get: documentation-repo
    trigger: true
  - get: hugo
    params:
      globs:
      - '*Linux-64bit.tar.gz'
  - task: compile-site
    file: documentation-repo/ci/tasks/hugo.yml
  - put: prod
    params:
      manifest: compiled-site/manifest.yml
      path: compiled-site
